import 'dotenv/config';
import { upsertFlower } from '../src/utils/pinecone';
import { FlowerData } from '../src/types/flower';

const flowers: FlowerData[] = [
  {
    id: 'alstroemeria-peruvian',
    name: 'Peruvian Lily',
    scientificName: 'Alstroemeria aurea',
    climate: ['Mediterranean', 'Temperate'],
    sunExposure: 'Full sun to partial shade',
    wateringNeeds: 'Moderate',
    soilType: 'Rich, well-draining',
    bloomingSeason: ['Summer', 'Fall'],
    hardiness: '7-10',
    description: 'Long-lasting cut flowers in various colors',
    imageUrl: 'https://images.unsplash.com/photo-1557968581-06d4b39ec0d6?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'hardy-geranium',
    name: 'Hardy Geranium',
    scientificName: 'Geranium Rozanne',
    climate: ['Temperate'],
    sunExposure: 'Full sun to partial shade',
    wateringNeeds: 'Moderate',
    soilType: 'Well-draining',
    bloomingSeason: ['Spring', 'Summer', 'Fall'],
    hardiness: '5-8',
    description: 'Long-blooming violet-blue flowers',
    imageUrl: 'https://images.unsplash.com/photo-1588695555293-55c5c6d7a58f?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'phlox-garden',
    name: 'Garden Phlox',
    scientificName: 'Phlox paniculata',
    climate: ['Temperate'],
    sunExposure: 'Full sun',
    wateringNeeds: 'Moderate',
    soilType: 'Rich, well-draining',
    bloomingSeason: ['Summer'],
    hardiness: '4-8',
    description: 'Fragrant clusters of pink, purple, or white flowers',
    imageUrl: 'https://images.unsplash.com/photo-1597176116047-876a32798fcc?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'campanula-bellflower',
    name: 'Canterbury Bells',
    scientificName: 'Campanula medium',
    climate: ['Temperate'],
    sunExposure: 'Full sun to partial shade',
    wateringNeeds: 'Moderate',
    soilType: 'Well-draining',
    bloomingSeason: ['Spring', 'Summer'],
    hardiness: '4-10',
    description: 'Bell-shaped flowers in blue, pink, or white',
    imageUrl: 'https://images.unsplash.com/photo-1597176116047-876a32798fcc?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'anemone-japanese',
    name: 'Japanese Anemone',
    scientificName: 'Anemone hupehensis',
    climate: ['Temperate'],
    sunExposure: 'Partial shade',
    wateringNeeds: 'Moderate',
    soilType: 'Rich, well-draining',
    bloomingSeason: ['Fall'],
    hardiness: '4-8',
    description: 'Late-blooming perennial with pink flowers',
    imageUrl: 'https://images.unsplash.com/photo-1599593752325-ffa41031056e?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'stokesia-stokes',
    name: 'Stokes Aster',
    scientificName: 'Stokesia laevis',
    climate: ['Temperate'],
    sunExposure: 'Full sun',
    wateringNeeds: 'Moderate',
    soilType: 'Well-draining',
    bloomingSeason: ['Summer', 'Fall'],
    hardiness: '5-9',
    description: 'Large blue cornflower-like blooms',
    imageUrl: 'https://images.unsplash.com/photo-1504196606672-aef5c9cefc92?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'monarda-bee-balm',
    name: 'Bee Balm',
    scientificName: 'Monarda didyma',
    climate: ['Temperate'],
    sunExposure: 'Full sun',
    wateringNeeds: 'Moderate',
    soilType: 'Rich, well-draining',
    bloomingSeason: ['Summer'],
    hardiness: '4-9',
    description: 'Aromatic red flowers attractive to pollinators',
    imageUrl: 'https://images.unsplash.com/photo-1594067603478-c5c0e8f80088?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'chrysanthemum-garden',
    name: 'Garden Mum',
    scientificName: 'Chrysanthemum x morifolium',
    climate: ['Temperate'],
    sunExposure: 'Full sun',
    wateringNeeds: 'Moderate',
    soilType: 'Well-draining',
    bloomingSeason: ['Fall'],
    hardiness: '5-9',
    description: 'Fall-blooming perennial with diverse flower forms',
    imageUrl: 'https://images.unsplash.com/photo-1508610048659-a06b669e3321?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'bougainvillea-purple',
    name: 'Purple Bougainvillea',
    scientificName: 'Bougainvillea glabra',
    climate: ['Mediterranean', 'Tropical'],
    sunExposure: 'Full sun',
    wateringNeeds: 'Low',
    soilType: 'Well-draining',
    bloomingSeason: ['Spring', 'Summer', 'Fall'],
    hardiness: '9-11',
    description: 'Vibrant climbing vine with purple bracts',
    imageUrl: 'https://images.unsplash.com/photo-1591857177580-dc82b9ac4e1e?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'jasmine-star',
    name: 'Star Jasmine',
    scientificName: 'Trachelospermum jasminoides',
    climate: ['Mediterranean', 'Subtropical'],
    sunExposure: 'Full sun to partial shade',
    wateringNeeds: 'Moderate',
    soilType: 'Well-draining',
    bloomingSeason: ['Spring', 'Summer'],
    hardiness: '8-10',
    description: 'Fragrant climbing vine with white star-shaped flowers',
    imageUrl: 'https://images.unsplash.com/photo-1525498128493-380d1990a112?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'oleander-pink',
    name: 'Pink Oleander',
    scientificName: 'Nerium oleander',
    climate: ['Mediterranean', 'Desert'],
    sunExposure: 'Full sun',
    wateringNeeds: 'Low',
    soilType: 'Well-draining',
    bloomingSeason: ['Spring', 'Summer', 'Fall'],
    hardiness: '8-10',
    description: 'Drought-tolerant shrub with pink flowers',
    imageUrl: 'https://images.unsplash.com/photo-1591857177580-dc82b9ac4e1e?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'coneflower-purple',
    name: 'Purple Coneflower',
    scientificName: 'Echinacea purpurea',
    climate: ['Temperate', 'Prairie'],
    sunExposure: 'Full sun',
    wateringNeeds: 'Low',
    soilType: 'Well-draining',
    bloomingSeason: ['Summer', 'Fall'],
    hardiness: '3-9',
    description: 'Native wildflower with purple daisy-like blooms',
    imageUrl: 'https://images.unsplash.com/photo-1597223557154-721c1cecc4b0?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'delphinium-pacific',
    name: 'Pacific Giant Delphinium',
    scientificName: 'Delphinium elatum',
    climate: ['Temperate'],
    sunExposure: 'Full sun',
    wateringNeeds: 'Moderate',
    soilType: 'Rich, well-draining',
    bloomingSeason: ['Summer'],
    hardiness: '3-7',
    description: 'Tall spikes of blue to purple flowers',
    imageUrl: 'https://images.unsplash.com/photo-1560717789-0ac7c58ac90a?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'iris-bearded',
    name: 'Bearded Iris',
    scientificName: 'Iris germanica',
    climate: ['Temperate', 'Mediterranean'],
    sunExposure: 'Full sun',
    wateringNeeds: 'Low',
    soilType: 'Well-draining',
    bloomingSeason: ['Spring'],
    hardiness: '3-10',
    description: 'Classic garden iris with ruffled petals',
    imageUrl: 'https://images.unsplash.com/photo-1557968581-06d4b39ec0d6?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'agastache-hummingbird',
    name: 'Hummingbird Mint',
    scientificName: 'Agastache rupestris',
    climate: ['Mediterranean', 'Desert'],
    sunExposure: 'Full sun',
    wateringNeeds: 'Low',
    soilType: 'Well-draining',
    bloomingSeason: ['Summer', 'Fall'],
    hardiness: '5-9',
    description: 'Aromatic foliage with orange-pink tubular flowers',
    imageUrl: 'https://images.unsplash.com/photo-1594067603478-c5c0e8f80088?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'stachys-lambs',
    name: 'Lambs Ears',
    scientificName: 'Stachys byzantina',
    climate: ['Mediterranean'],
    sunExposure: 'Full sun',
    wateringNeeds: 'Low',
    soilType: 'Well-draining',
    bloomingSeason: ['Summer'],
    hardiness: '4-8',
    description: 'Soft, woolly silver foliage plant',
    imageUrl: 'https://images.unsplash.com/photo-1591857177580-dc82b9ac4e1e?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'rose-1',
    name: 'Hybrid Tea Rose',
    scientificName: 'Rosa hybrid',
    climate: ['Temperate', 'Continental'],
    sunExposure: 'Full Sun',
    wateringNeeds: 'Moderate',
    soilType: 'Rich, Well-draining',
    bloomingSeason: ['Late Spring', 'Summer', 'Fall'],
    hardiness: '6-9',
    description: 'Classic long-stemmed roses with large, shapely blooms',
    imageUrl: 'https://images.unsplash.com/photo-1496062031456-07b8f162a322?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'liatris-blazing',
    name: 'Blazing Star',
    scientificName: 'Liatris spicata',
    climate: ['Prairie', 'Temperate'],
    sunExposure: 'Full sun',
    wateringNeeds: 'Moderate',
    soilType: 'Well-draining',
    bloomingSeason: ['Summer'],
    hardiness: '3-9',
    description: 'Tall purple flower spikes',
    imageUrl: 'https://images.unsplash.com/photo-1597176116047-876a32798fcc?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'platycodon-balloon',
    name: 'Balloon Flower',
    scientificName: 'Platycodon grandiflorus',
    climate: ['Temperate'],
    sunExposure: 'Full sun to partial shade',
    wateringNeeds: 'Moderate',
    soilType: 'Well-draining',
    bloomingSeason: ['Summer'],
    hardiness: '3-8',
    description: 'Blue balloon-like buds that open to star-shaped flowers',
    imageUrl: 'https://images.unsplash.com/photo-1562690868-60bbe7293e94?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'papaver-oriental',
    name: 'Oriental Poppy',
    scientificName: 'Papaver orientale',
    climate: ['Temperate'],
    sunExposure: 'Full sun',
    wateringNeeds: 'Low',
    soilType: 'Well-draining',
    bloomingSeason: ['Spring', 'Early Summer'],
    hardiness: '3-7',
    description: 'Large silky orange-red flowers',
    imageUrl: 'https://images.unsplash.com/photo-1557968581-06d4b39ec0d6?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'thalictrum-meadow',
    name: 'Meadow Rue',
    scientificName: 'Thalictrum aquilegifolium',
    climate: ['Temperate'],
    sunExposure: 'Partial shade',
    wateringNeeds: 'Moderate',
    soilType: 'Rich, well-draining',
    bloomingSeason: ['Summer'],
    hardiness: '5-9',
    description: 'Airy purple flowers with white stamens',
    imageUrl: 'https://images.unsplash.com/photo-1597223557154-721c1cecc4b0?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'daylily-stella',
    name: 'Stella dOro Daylily',
    scientificName: 'Hemerocallis Stella dOro',
    climate: ['Temperate'],
    sunExposure: 'Full sun',
    wateringNeeds: 'Moderate',
    soilType: 'Adaptable',
    bloomingSeason: ['Spring', 'Summer', 'Fall'],
    hardiness: '3-10',
    description: 'Reblooming yellow daylily',
    imageUrl: 'https://images.unsplash.com/photo-1530092285049-1c42085fd395?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'gaillardia-blanket',
    name: 'Blanket Flower',
    scientificName: 'Gaillardia x grandiflora',
    climate: ['Prairie', 'Mediterranean'],
    sunExposure: 'Full sun',
    wateringNeeds: 'Low',
    soilType: 'Well-draining',
    bloomingSeason: ['Summer', 'Fall'],
    hardiness: '3-10',
    description: 'Red and yellow daisy-like flowers',
    imageUrl: 'https://images.unsplash.com/photo-1563241527-3004b7be0ffd?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'verbena-bonariensis',
    name: 'Tall Verbena',
    scientificName: 'Verbena bonariensis',
    climate: ['Mediterranean', 'Temperate'],
    sunExposure: 'Full sun',
    wateringNeeds: 'Low',
    soilType: 'Well-draining',
    bloomingSeason: ['Summer', 'Fall'],
    hardiness: '7-11',
    description: 'Tall, airy purple flower clusters',
    imageUrl: 'https://images.unsplash.com/photo-1597223557154-721c1cecc4b0?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'veronica-speedwell',
    name: 'Speedwell',
    scientificName: 'Veronica spicata',
    climate: ['Temperate'],
    sunExposure: 'Full sun',
    wateringNeeds: 'Moderate',
    soilType: 'Well-draining',
    bloomingSeason: ['Summer'],
    hardiness: '3-8',
    description: 'Spikes of small blue flowers',
    imageUrl: 'https://images.unsplash.com/photo-1533792344354-ed5e8fc12494?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'gaura-pink',
    name: 'Pink Gaura',
    scientificName: 'Gaura lindheimeri',
    climate: ['Mediterranean', 'Prairie'],
    sunExposure: 'Full sun',
    wateringNeeds: 'Low',
    soilType: 'Well-draining',
    bloomingSeason: ['Spring', 'Summer', 'Fall'],
    hardiness: '5-9',
    description: 'Airy wands of pink butterfly-like flowers',
    imageUrl: 'https://images.unsplash.com/photo-1591857177580-dc82b9ac4e1e?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'thymus-creeping',
    name: 'Creeping Thyme',
    scientificName: 'Thymus serpyllum',
    climate: ['Mediterranean'],
    sunExposure: 'Full sun',
    wateringNeeds: 'Low',
    soilType: 'Well-draining',
    bloomingSeason: ['Summer'],
    hardiness: '4-9',
    description: 'Low-growing aromatic herb with tiny pink flowers',
    imageUrl: 'https://images.unsplash.com/photo-1533792344354-ed5e8fc12494?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'kniphofia-red-hot',
    name: 'Red Hot Poker',
    scientificName: 'Kniphofia uvaria',
    climate: ['Mediterranean'],
    sunExposure: 'Full sun',
    wateringNeeds: 'Low',
    soilType: 'Well-draining',
    bloomingSeason: ['Summer', 'Fall'],
    hardiness: '6-9',
    description: 'Torch-like spikes of orange and yellow flowers',
    imageUrl: 'https://images.unsplash.com/photo-1563241527-3004b7be0ffd?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'lavender-1',
    name: 'English Lavender',
    scientificName: 'Lavandula angustifolia',
    climate: ['Mediterranean', 'Temperate'],
    sunExposure: 'Full Sun',
    wateringNeeds: 'Low',
    soilType: 'Well-draining',
    bloomingSeason: ['Late Spring', 'Summer'],
    hardiness: '5-8',
    description: 'Fragrant purple flowers perfect for borders and herb gardens',
    imageUrl: 'https://images.unsplash.com/photo-1499002238440-d264edd596ec?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'dianthus-pink',
    name: 'Garden Pink',
    scientificName: 'Dianthus gratianopolitanus',
    climate: ['Mediterranean', 'Temperate'],
    sunExposure: 'Full sun',
    wateringNeeds: 'Low',
    soilType: 'Well-draining',
    bloomingSeason: ['Spring', 'Summer'],
    hardiness: '3-9',
    description: 'Fragrant pink flowers with fringed petals',
    imageUrl: 'https://images.unsplash.com/photo-1557968581-06d4b39ec0d6?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'alpine-forget-me-not',
    name: 'Alpine Forget-me-not',
    scientificName: 'Myosotis alpestris',
    climate: ['Alpine'],
    sunExposure: 'Full sun to partial shade',
    wateringNeeds: 'Moderate',
    soilType: 'Well-draining',
    bloomingSeason: ['Spring', 'Summer'],
    hardiness: '3-6',
    description: 'Delicate blue flowers perfect for rock gardens',
    imageUrl: 'https://images.unsplash.com/photo-1557968581-06d4b39ec0d6?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'leucanthemum-shasta',
    name: 'Shasta Daisy',
    scientificName: 'Leucanthemum x superbum',
    climate: ['Temperate'],
    sunExposure: 'Full sun',
    wateringNeeds: 'Moderate',
    soilType: 'Well-draining',
    bloomingSeason: ['Summer'],
    hardiness: '5-9',
    description: 'Classic white daisy with yellow center',
    imageUrl: 'https://images.unsplash.com/photo-1508610048659-a06b669e3321?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'climbing-rose',
    name: 'Climbing Rose',
    scientificName: 'Rosa multiflora',
    climate: ['Temperate', 'Mediterranean'],
    sunExposure: 'Full sun',
    wateringNeeds: 'Moderate',
    soilType: 'Rich, well-draining',
    bloomingSeason: ['Spring', 'Summer', 'Fall'],
    hardiness: '5-9',
    description: 'Vigorous climbing rose with clusters of small flowers',
    imageUrl: 'https://images.unsplash.com/photo-1496062031456-07b8f162a322?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'penstemon-red',
    name: 'Red Penstemon',
    scientificName: 'Penstemon barbatus',
    climate: ['Mediterranean', 'Desert'],
    sunExposure: 'Full sun',
    wateringNeeds: 'Low',
    soilType: 'Well-draining',
    bloomingSeason: ['Summer'],
    hardiness: '4-9',
    description: 'Red tubular flowers attractive to hummingbirds',
    imageUrl: 'https://images.unsplash.com/photo-1563241527-3004b7be0ffd?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'teucrium-germander',
    name: 'Wall Germander',
    scientificName: 'Teucrium chamaedrys',
    climate: ['Mediterranean'],
    sunExposure: 'Full sun',
    wateringNeeds: 'Low',
    soilType: 'Well-draining',
    bloomingSeason: ['Summer'],
    hardiness: '5-9',
    description: 'Low-growing herb with pink-purple flowers',
    imageUrl: 'https://images.unsplash.com/photo-1533792344354-ed5e8fc12494?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'plumeria-tropical',
    name: 'Tropical Plumeria',
    scientificName: 'Plumeria rubra',
    climate: ['Tropical'],
    sunExposure: 'Full sun',
    wateringNeeds: 'Moderate',
    soilType: 'Well-draining',
    bloomingSeason: ['Spring', 'Summer', 'Fall'],
    hardiness: '9-11',
    description: 'Fragrant tropical flower with pink and white blooms',
    imageUrl: 'https://images.unsplash.com/photo-1546938576-6e6a64f317cc?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'lavender-french',
    name: 'French Lavender',
    scientificName: 'Lavandula dentata',
    climate: ['Mediterranean', 'Coastal'],
    sunExposure: 'Full sun',
    wateringNeeds: 'Low',
    soilType: 'Well-draining',
    bloomingSeason: ['Spring', 'Summer'],
    hardiness: '8-9',
    description: 'Aromatic herb with toothed leaves and purple flowers',
    imageUrl: 'https://images.unsplash.com/photo-1499002238440-d264edd596ec?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'peony-tree',
    name: 'Tree Peony',
    scientificName: 'Paeonia suffruticosa',
    climate: ['Temperate'],
    sunExposure: 'Partial shade',
    wateringNeeds: 'Moderate',
    soilType: 'Rich, well-draining',
    bloomingSeason: ['Spring'],
    hardiness: '4-9',
    description: 'Woody shrub with large, showy flowers',
    imageUrl: 'https://images.unsplash.com/photo-1490750967868-88aa4486c946?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'nepeta-catmint',
    name: 'Walkers Low Catmint',
    scientificName: 'Nepeta cataria',
    climate: ['Mediterranean'],
    sunExposure: 'Full sun',
    wateringNeeds: 'Low',
    soilType: 'Well-draining',
    bloomingSeason: ['Summer'],
    hardiness: '4-8',
    description: 'Fragrant gray-green foliage with lavender-blue flowers',
    imageUrl: 'https://images.unsplash.com/photo-1594067603478-c5c0e8f80088?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'physostegia-obedient',
    name: 'Obedient Plant',
    scientificName: 'Physostegia virginiana',
    climate: ['Temperate'],
    sunExposure: 'Full sun',
    wateringNeeds: 'Moderate',
    soilType: 'Well-draining',
    bloomingSeason: ['Summer'],
    hardiness: '4-8',
    description: 'Spikes of pink snapdragon-like flowers',
    imageUrl: 'https://images.unsplash.com/photo-1525498128493-380d1990a112?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'desert-marigold',
    name: 'Desert Marigold',
    scientificName: 'Tagetes patula',
    climate: ['Desert'],
    sunExposure: 'Full sun',
    wateringNeeds: 'Low',
    soilType: 'Well-draining',
    bloomingSeason: ['Summer'],
    hardiness: '6-10',
    description: 'Yellow daisy-like flowers on silver foliage',
    imageUrl: 'https://images.unsplash.com/photo-1597848212624-a19eb35e2651?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'digitalis-foxglove',
    name: 'Common Foxglove',
    scientificName: 'Digitalis purpurea',
    climate: ['Temperate'],
    sunExposure: 'Full sun',
    wateringNeeds: 'Moderate',
    soilType: 'Well-draining',
    bloomingSeason: ['Spring', 'Summer'],
    hardiness: '4-8',
    description: 'Tall spikes of tubular pink flowers',
    imageUrl: 'https://images.unsplash.com/photo-1525498128493-380d1990a112?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'heliconia-tropical',
    name: 'Tropical Heliconia',
    scientificName: 'Heliconia rostrata',
    climate: ['Tropical'],
    sunExposure: 'Full sun',
    wateringNeeds: 'Moderate',
    soilType: 'Well-draining',
    bloomingSeason: ['Spring', 'Summer'],
    hardiness: '8-10',
    description: 'Exotic red and yellow bird-like flowers',
    imageUrl: 'https://images.unsplash.com/photo-1596738317850-3292d5dcd755?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'lantana-multicolor',
    name: 'Multicolor Lantana',
    scientificName: 'Lantana camara',
    climate: ['Tropical'],
    sunExposure: 'Full sun',
    wateringNeeds: 'Low',
    soilType: 'Well-draining',
    bloomingSeason: ['Spring', 'Summer'],
    hardiness: '8-10',
    description: 'Clusters of small flowers in mixed colors',
    imageUrl: 'https://images.unsplash.com/photo-1525498128493-380d1990a112?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'echinacea-white',
    name: 'White Coneflower',
    scientificName: 'Echinacea purpurea',
    climate: ['Temperate', 'Prairie'],
    sunExposure: 'Full sun',
    wateringNeeds: 'Low',
    soilType: 'Well-draining',
    bloomingSeason: ['Summer', 'Fall'],
    hardiness: '3-9',
    description: 'White daisy-like flowers with orange cones',
    imageUrl: 'https://images.unsplash.com/photo-1597223557154-721c1cecc4b0?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'heuchera-coral',
    name: 'Coral Bells',
    scientificName: 'Heuchera sanguinea',
    climate: ['Temperate'],
    sunExposure: 'Partial shade',
    wateringNeeds: 'Moderate',
    soilType: 'Well-draining',
    bloomingSeason: ['Spring', 'Summer'],
    hardiness: '4-9',
    description: 'Colorful foliage with tiny bell-shaped flowers',
    imageUrl: 'https://images.unsplash.com/photo-1557968581-06d4b39ec0d6?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'rudbeckia-black',
    name: 'Black-Eyed Susan',
    scientificName: 'Rudbeckia hirta',
    climate: ['Temperate'],
    sunExposure: 'Full sun',
    wateringNeeds: 'Low',
    soilType: 'Well-draining',
    bloomingSeason: ['Summer'],
    hardiness: '4-8',
    description: 'Yellow daisy-like flowers with dark centers',
    imageUrl: 'https://images.unsplash.com/photo-1534710961216-75c88202f43e?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'prairie-coneflower',
    name: 'Prairie Coneflower',
    scientificName: 'Ratibida pinnata',
    climate: ['Prairie'],
    sunExposure: 'Full sun',
    wateringNeeds: 'Low',
    soilType: 'Well-draining',
    bloomingSeason: ['Summer'],
    hardiness: '3-8',
    description: 'Yellow drooping petals with prominent cones',
    imageUrl: 'https://images.unsplash.com/photo-1525498128493-380d1990a112?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'astilbe-pink',
    name: 'Pink Astilbe',
    scientificName: 'Astilbe chinensis',
    climate: ['Temperate'],
    sunExposure: 'Partial shade',
    wateringNeeds: 'High',
    soilType: 'Rich, moist',
    bloomingSeason: ['Summer'],
    hardiness: '4-8',
    description: 'Feathery pink plumes',
    imageUrl: 'https://images.unsplash.com/photo-1596738317850-3292d5dcd755?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'barrel-cactus',
    name: 'Golden Barrel Cactus',
    scientificName: 'Echinocereus stramineus',
    climate: ['Desert'],
    sunExposure: 'Full sun',
    wateringNeeds: 'Low',
    soilType: 'Well-draining',
    bloomingSeason: ['Spring', 'Summer'],
    hardiness: '8-10',
    description: 'Round cactus with golden spines',
    imageUrl: 'https://images.unsplash.com/photo-1509223197845-458d87318791?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'sedum-autumn',
    name: 'Autumn Joy Sedum',
    scientificName: 'Sedum spectabile',
    climate: ['Temperate'],
    sunExposure: 'Full sun',
    wateringNeeds: 'Low',
    soilType: 'Well-draining',
    bloomingSeason: ['Summer', 'Fall'],
    hardiness: '3-9',
    description: 'Succulent with pink flower clusters',
    imageUrl: 'https://images.unsplash.com/photo-1509223197845-458d87318791?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'dahlia-dinner-plate',
    name: 'Dinner Plate Dahlia',
    scientificName: 'Dahlia spp.',
    climate: ['Temperate'],
    sunExposure: 'Full sun',
    wateringNeeds: 'Moderate',
    soilType: 'Well-draining',
    bloomingSeason: ['Summer'],
    hardiness: '5-9',
    description: 'Large, showy flowers up to 10 inches across',
    imageUrl: 'https://images.unsplash.com/photo-1597848212624-a19eb35e2651?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'achillea-yellow',
    name: 'Yellow Yarrow',
    scientificName: 'Achillea filipendulina',
    climate: ['Mediterranean', 'Prairie'],
    sunExposure: 'Full sun',
    wateringNeeds: 'Low',
    soilType: 'Well-draining',
    bloomingSeason: ['Summer'],
    hardiness: '3-8',
    description: 'Flat-topped clusters of yellow flowers',
    imageUrl: 'https://images.unsplash.com/photo-1533792344354-ed5e8fc12494?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'siberian-iris',
    name: 'Siberian Iris',
    scientificName: 'Iris sibirica',
    climate: ['Temperate'],
    sunExposure: 'Full sun',
    wateringNeeds: 'Low',
    soilType: 'Well-draining',
    bloomingSeason: ['Spring'],
    hardiness: '3-8',
    description: 'Elegant blue-purple flowers with grass-like foliage',
    imageUrl: 'https://images.unsplash.com/photo-1557968581-06d4b39ec0d6?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'edelweiss',
    name: 'Edelweiss',
    scientificName: 'Leontopodium alpinum',
    climate: ['Alpine'],
    sunExposure: 'Full sun',
    wateringNeeds: 'Low',
    soilType: 'Well-draining',
    bloomingSeason: ['Summer'],
    hardiness: '4-7',
    description: 'White star-shaped flowers with woolly bracts',
    imageUrl: 'https://images.unsplash.com/photo-1597223557154-721c1cecc4b0?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'agapanthus-lily',
    name: 'Lily of the Nile',
    scientificName: 'Agapanthus africanus',
    climate: ['Mediterranean'],
    sunExposure: 'Full sun',
    wateringNeeds: 'Moderate',
    soilType: 'Well-draining',
    bloomingSeason: ['Summer'],
    hardiness: '7-11',
    description: 'Blue or white ball-shaped flower clusters',
    imageUrl: 'https://images.unsplash.com/photo-1596738317850-3292d5dcd755?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'gentiana-alpine',
    name: 'Alpine Gentian',
    scientificName: 'Gentiana acaulis',
    climate: ['Alpine'],
    sunExposure: 'Full sun',
    wateringNeeds: 'Moderate',
    soilType: 'Well-draining',
    bloomingSeason: ['Spring', 'Summer'],
    hardiness: '3-7',
    description: 'Deep blue trumpet-shaped flowers',
    imageUrl: 'https://images.unsplash.com/photo-1591857177580-dc82b9ac4e1e?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'phlomis-sage',
    name: 'Jerusalem Sage',
    scientificName: 'Phlomis fruticosa',
    climate: ['Mediterranean'],
    sunExposure: 'Full sun',
    wateringNeeds: 'Low',
    soilType: 'Well-draining',
    bloomingSeason: ['Summer'],
    hardiness: '7-9',
    description: 'Whorls of yellow flowers with woolly leaves',
    imageUrl: 'https://images.unsplash.com/photo-1594067603478-c5c0e8f80088?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'russian-sage-continental',
    name: 'Continental Russian Sage',
    scientificName: 'Salvia spp.',
    climate: ['Temperate'],
    sunExposure: 'Full sun',
    wateringNeeds: 'Low',
    soilType: 'Well-draining',
    bloomingSeason: ['Spring', 'Summer'],
    hardiness: '5-9',
    description: 'Spikes of small lavender-blue flowers',
    imageUrl: 'https://images.unsplash.com/photo-1594067603478-c5c0e8f80088?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'salvia-mexican',
    name: 'Mexican Bush Sage',
    scientificName: 'Salvia leucantha',
    climate: ['Temperate'],
    sunExposure: 'Full sun',
    wateringNeeds: 'Low',
    soilType: 'Well-draining',
    bloomingSeason: ['Spring', 'Summer'],
    hardiness: '5-9',
    description: 'Velvety purple flower spikes',
    imageUrl: 'https://images.unsplash.com/photo-1594067603478-c5c0e8f80088?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'salvia-russian',
    name: 'Russian Sage',
    scientificName: 'Salvia spp.',
    climate: ['Temperate'],
    sunExposure: 'Full sun',
    wateringNeeds: 'Low',
    soilType: 'Well-draining',
    bloomingSeason: ['Spring', 'Summer'],
    hardiness: '5-9',
    description: 'Airy spikes of lavender-blue flowers',
    imageUrl: 'https://images.unsplash.com/photo-1594067603478-c5c0e8f80088?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'hosta-blue',
    name: 'Blue Hosta',
    scientificName: 'Hosta sieboldiana',
    climate: ['Temperate'],
    sunExposure: 'Shade',
    wateringNeeds: 'Moderate',
    soilType: 'Rich, well-draining',
    bloomingSeason: ['Summer'],
    hardiness: '3-8',
    description: 'Large blue-green leaves with white flowers',
    imageUrl: 'https://images.unsplash.com/photo-1594067603478-c5c0e8f80088?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'fern-japanese',
    name: 'Japanese Painted Fern',
    scientificName: 'Athyrium niponicum',
    climate: ['Temperate'],
    sunExposure: 'Shade',
    wateringNeeds: 'Moderate',
    soilType: 'Rich, well-draining',
    bloomingSeason: ['Non-flowering'],
    hardiness: '4-9',
    description: 'Silver and burgundy fronds with delicate texture',
    imageUrl: 'https://images.unsplash.com/photo-1597223557154-721c1cecc4b0?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'bleeding-heart',
    name: 'Bleeding Heart',
    scientificName: 'Dicentra spectabilis',
    climate: ['Temperate'],
    sunExposure: 'Partial shade',
    wateringNeeds: 'Moderate',
    soilType: 'Rich, well-draining',
    bloomingSeason: ['Spring'],
    hardiness: '3-9',
    description: 'Pink heart-shaped flowers on arching stems',
    imageUrl: 'https://images.unsplash.com/photo-1591857177580-dc82b9ac4e1e?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'hellebore-lenten',
    name: 'Lenten Rose',
    scientificName: 'Helleborus orientalis',
    climate: ['Temperate'],
    sunExposure: 'Partial shade to shade',
    wateringNeeds: 'Moderate',
    soilType: 'Rich, well-draining',
    bloomingSeason: ['Winter', 'Spring'],
    hardiness: '4-9',
    description: 'Winter-blooming perennial with purple-pink flowers',
    imageUrl: 'https://images.unsplash.com/photo-1594067603478-c5c0e8f80088?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'tiarella-foamflower',
    name: 'Foamflower',
    scientificName: 'Tiarella cordifolia',
    climate: ['Temperate'],
    sunExposure: 'Shade',
    wateringNeeds: 'Moderate',
    soilType: 'Rich, well-draining',
    bloomingSeason: ['Spring'],
    hardiness: '4-9',
    description: 'Delicate white flower spikes above maple-like leaves',
    imageUrl: 'https://images.unsplash.com/photo-1533792344354-ed5e8fc12494?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'brunnera-jack-frost',
    name: 'Jack Frost Brunnera',
    scientificName: 'Brunnera macrophylla',
    climate: ['Temperate'],
    sunExposure: 'Partial shade to shade',
    wateringNeeds: 'Moderate',
    soilType: 'Rich, well-draining',
    bloomingSeason: ['Spring'],
    hardiness: '3-8',
    description: 'Silver leaves with delicate blue forget-me-not flowers',
    imageUrl: 'https://images.unsplash.com/photo-1597223557154-721c1cecc4b0?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'pulmonaria-lungwort',
    name: 'Lungwort',
    scientificName: 'Pulmonaria officinalis',
    climate: ['Temperate'],
    sunExposure: 'Partial shade to shade',
    wateringNeeds: 'Moderate',
    soilType: 'Rich, well-draining',
    bloomingSeason: ['Spring'],
    hardiness: '4-8',
    description: 'Spotted leaves with pink and blue flowers',
    imageUrl: 'https://images.unsplash.com/photo-1594067603478-c5c0e8f80088?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'heuchera-purple',
    name: 'Purple Palace Coral Bells',
    scientificName: 'Heuchera micrantha',
    climate: ['Temperate'],
    sunExposure: 'Partial shade',
    wateringNeeds: 'Moderate',
    soilType: 'Well-draining',
    bloomingSeason: ['Summer'],
    hardiness: '4-9',
    description: 'Deep purple foliage with tiny pink flowers',
    imageUrl: 'https://images.unsplash.com/photo-1557968581-06d4b39ec0d6?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'aquilegia-columbine',
    name: 'Columbine',
    scientificName: 'Aquilegia canadensis',
    climate: ['Temperate'],
    sunExposure: 'Partial sun',
    wateringNeeds: 'Moderate',
    soilType: 'Rich, well-draining',
    bloomingSeason: ['Spring', 'Early Summer'],
    hardiness: '3-8',
    description: 'Red and yellow spurred flowers on delicate stems',
    imageUrl: 'https://images.unsplash.com/photo-1557968581-06d4b39ec0d6?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'polygonatum-solomon',
    name: 'Solomon\'s Seal',
    scientificName: 'Polygonatum odoratum',
    climate: ['Temperate'],
    sunExposure: 'Partial sun',
    wateringNeeds: 'Moderate',
    soilType: 'Rich, well-draining',
    bloomingSeason: ['Spring'],
    hardiness: '3-8',
    description: 'Arching stems with dangling white bell flowers',
    imageUrl: 'https://images.unsplash.com/photo-1597223557154-721c1cecc4b0?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'tricyrtis-toad',
    name: 'Toad Lily',
    scientificName: 'Tricyrtis hirta',
    climate: ['Temperate'],
    sunExposure: 'Partial sun',
    wateringNeeds: 'Moderate',
    soilType: 'Rich, well-draining',
    bloomingSeason: ['Fall'],
    hardiness: '4-8',
    description: 'Orchid-like spotted flowers in purple and white',
    imageUrl: 'https://images.unsplash.com/photo-1594067603478-c5c0e8f80088?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'kirengeshoma-palmata',
    name: 'Yellow Waxbells',
    scientificName: 'Kirengeshoma palmata',
    climate: ['Temperate'],
    sunExposure: 'Partial sun',
    wateringNeeds: 'Moderate',
    soilType: 'Rich, well-draining',
    bloomingSeason: ['Late Summer', 'Fall'],
    hardiness: '5-8',
    description: 'Maple-like leaves with waxy yellow bell flowers',
    imageUrl: 'https://images.unsplash.com/photo-1533792344354-ed5e8fc12494?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'chelone-turtlehead',
    name: 'Pink Turtlehead',
    scientificName: 'Chelone lyonii',
    climate: ['Temperate'],
    sunExposure: 'Partial sun',
    wateringNeeds: 'Moderate to high',
    soilType: 'Rich, moist',
    bloomingSeason: ['Late Summer', 'Fall'],
    hardiness: '3-8',
    description: 'Pink hooded flowers resembling turtle heads',
    imageUrl: 'https://images.unsplash.com/photo-1597223557154-721c1cecc4b0?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'aconitum-monkshood',
    name: 'Monkshood',
    scientificName: 'Aconitum napellus',
    climate: ['Temperate'],
    sunExposure: 'Partial sun',
    wateringNeeds: 'Moderate',
    soilType: 'Rich, well-draining',
    bloomingSeason: ['Late Summer', 'Fall'],
    hardiness: '3-7',
    description: 'Deep blue hooded flowers on tall spikes',
    imageUrl: 'https://images.unsplash.com/photo-1594067603478-c5c0e8f80088?auto=format&fit=crop&w=800&q=80'
  }
];

async function seedFlowers() {
  console.log('Starting to seed flowers...');
  let successCount = 0;
  let errorCount = 0;
  
  for (const flower of flowers) {
    try {
      await upsertFlower(flower);
      console.log(`Successfully seeded ${flower.name}`);
      successCount++;
    } catch (error) {
      console.error(`Error seeding ${flower.name}:`, error);
      errorCount++;
    }
  }
  
  console.log(`Finished seeding flowers. Success: ${successCount}, Errors: ${errorCount}`);
}

// Run the seeding function
seedFlowers().catch(console.error); 